import { ArchivedLetter } from '../types/archive';
import { generateSampleIncomingLetterCanvas } from './pdfHelper';

export function getInitialSeedLetters(): ArchivedLetter[] {
  const sampleCanvas1 = generateSampleIncomingLetterCanvas(
    '1452/و',
    'وز/ت/892',
    '2026/05/18',
    '2026/05/20',
    'بشأن تخصيص الميزانية التشغيلية وتوريد أجهزة المسح الضوئي والأرشفة',
    'وزارة التخطيط والمالية - الإدارة العامة للموازنة',
    'وزارة الاتصالات وتقنية المعلومات - دائرة نظم المعلومات'
  );

  const sampleCanvas2 = generateSampleIncomingLetterCanvas(
    '2089/و',
    'هـ/رق/512',
    '2026/05/14',
    '2026/05/15',
    'اعتماد الدليل الإجرائي الموحد لأمن الوثائق والسرية الإلكترونية',
    'الهيئة الوطنية للأمن السيبراني والتحول الرقمي',
    'كافة الوزارات والهيئات والمؤسسات الحكومية'
  );

  return [
    {
      id: 'doc-001',
      type: 'وارد',
      incomingNumber: '1452/و',
      outgoingNumber: 'وز/ت/892',
      letterDate: '2026-05-18',
      receiptDate: '2026-05-20',
      subject: 'بشأن تخصيص الميزانية التشغيلية وتوريد أجهزة المسح الضوئي والأرشفة',
      senderEntity: 'وزارة التخطيط والمالية - الإدارة العامة للموازنة',
      recipientEntity: 'وزارة الاتصالات وتقنية المعلومات - دائرة نظم المعلومات',
      priority: 'عاجل وسري للغاية',
      category: 'مالي وتقني',
      status: 'قيد الإجراء',
      summary: 'الموافقة على تخصيص مبلغ 480,000 ريال/دينار لتوريد ماسحات ضوئية عالية السرعة ماركة Fujitsu وتفعيل نظام التعرف الضوئي OCR لقراءة أختام الوارد الزرقاء، مع إلزام الدائرة بتقديم تقرير الإنجاز قبل 2026/06/15.',
      actionRequired: 'اتخاذ اللازم للتعاقد واستلام الشحنة وإعداد تقرير دوري',
      keywords: ['ميزانية تشغيلية', 'ماسحات ضوئية', 'Fujitsu', 'أرشفة ذكية', 'OCR الختم الأزرق', 'تحول رقمي'],
      importantNumbers: [
        { label: 'رقم الأمر الإداري', value: 'م.ع/4502' },
        { label: 'مبلغ الميزانية المعتمدة', value: '480,000 ريال/دينار' },
        { label: 'الموعد النهائي للتقرير', value: '2026/06/15' },
        { label: 'عدد صفحات المرفقات', value: '25 صفحة' },
      ],
      followUpAssignees: [
        {
          entityName: 'دائرة الشؤون المالية والحسابات',
          assignedAction: 'لصرف الدفعة الأولى وفق جدول التدفقات النقدية',
          deadline: '2026/05/28',
          status: 'قيد المتابعة',
        },
        {
          entityName: 'قسم المشتريات والمناقصات المركزية',
          assignedAction: 'لاستكمال إجراءات التعاقد والتوريد الفني',
          deadline: '2026/06/05',
          status: 'عاجل',
        },
        {
          entityName: 'شعبة الدعم الفني والأرشفة',
          assignedAction: 'لإعداد البنية التحتية وتوزيع الماسحات على المكاتب',
          status: 'قيد المتابعة',
        },
      ],
      attachments: ['جدول الكميات والمواصفات الفنية', 'محضر لجنة الفحص والترسية', 'كشف التدفق النقدي'],
      blueStamp: {
        detected: true,
        handwrittenIncomingNumber: '1452/و',
        handwrittenReceiptDate: '2026/05/20',
        stampPrintedText: 'وارد ديوان الوزارة العام - شعبة التسجيل والتوثيق الإلكتروني',
        confidence: 98,
        notes: 'الختم الأزرق واضح جداً في أعلى الصفحة مع كتابة يدوية صريحة وتوقيع الموظف المستلم.',
        boundingBox: {
          topPercent: 12.8,
          leftPercent: 7.5,
          widthPercent: 27,
          heightPercent: 10.5,
        },
      },
      pageImages: [sampleCanvas1],
      pdfFileName: 'كتاب_وارد_ميزانية_الماسحات_1452.pdf',
      pdfFileSize: 412000,
      createdAt: '2026-05-20T08:30:00.000Z',
      updatedAt: '2026-05-20T08:30:00.000Z',
    },
    {
      id: 'doc-002',
      type: 'صادر',
      incomingNumber: '-',
      outgoingNumber: 'ص/2026/410',
      letterDate: '2026-05-19',
      receiptDate: '-',
      subject: 'إشعار بإتمام المرحلة التجريبية لنظام أرشفة البريد الصادر والوارد',
      senderEntity: 'دائرة نظم وتقنية المعلومات',
      recipientEntity: 'مكتب معالي الوزير المحترم',
      priority: 'عادي',
      category: 'إداري وتطوير',
      status: 'تم الرد',
      summary: 'إحاطة معالي الوزير باكتمال تشغيل منظومة الأرشفة الذكية وتدريب 45 موظفاً على معالجة البريد اليومي واستخراج الكلمات المفتاحية والأختام تلقائياً.',
      actionRequired: 'للعلم والاطلاع والتوجيه بما يلزم',
      keywords: ['نظام الأرشفة', 'المرحلة التجريبية', 'تدريب الموظفين', 'البريد الصادر', 'تحسين الأداء'],
      importantNumbers: [
        { label: 'رقم الكتاب الصادر', value: 'ص/2026/410' },
        { label: 'عدد الموظفين المتدربين', value: '45 موظف' },
        { label: 'نسبة الإنجاز', value: '100%' },
      ],
      followUpAssignees: [
        {
          entityName: 'مدير مكتب الوزير',
          assignedAction: 'للعرض على معالي الوزير والتوجيه',
          status: 'مكتمل',
        },
        {
          entityName: 'دائرة التطوير الإداري والتدريب',
          assignedAction: 'لأرشفة تقارير المتدربين وإصدار الشهادات',
          status: 'مكتمل',
        },
      ],
      attachments: ['تقرير إحصائي تفصيلي عن تجربة النظام', 'قائمة بأسماء الموظفين المتدربين'],
      blueStamp: {
        detected: false,
        handwrittenIncomingNumber: '',
        handwrittenReceiptDate: '',
      },
      pageImages: [sampleCanvas2],
      pdfFileName: 'كتاب_صادر_إتمام_المرحلة_التجريبية.pdf',
      pdfFileSize: 298000,
      createdAt: '2026-05-19T10:15:00.000Z',
      updatedAt: '2026-05-19T10:15:00.000Z',
    },
    {
      id: 'doc-003',
      type: 'وارد',
      incomingNumber: '2089/و',
      outgoingNumber: 'هـ/رق/512',
      letterDate: '2026-05-14',
      receiptDate: '2026-05-15',
      subject: 'اعتماد الدليل الإجرائي الموحد لأمن الوثائق والسرية الإلكترونية',
      senderEntity: 'الهيئة الوطنية للأمن السيبراني والتحول الرقمي',
      recipientEntity: 'كافة الوزارات والهيئات والمؤسسات الحكومية',
      priority: 'سري',
      category: 'أمن معلومات وقوانين',
      status: 'مؤرشف',
      summary: 'إلزام جميع الجهات الحكومية بتطبيق بروتوكولات التشفير وحفظ الأرشيف الرقمي الصادر والوارد وفق معايير الأمان المعتمدة في اللائحة التنفيذية رقم 18 لسنة 2026.',
      actionRequired: 'تطبيق التوصيات والتنسيق مع ضابط أمن المعلومات',
      keywords: ['أمن الوثائق', 'الهيئة الوطنية للأمن السيبراني', 'سرية إلكترونية', 'لائحة تنفيذية', 'تشفير الأرشيف'],
      importantNumbers: [
        { label: 'رقم اللائحة التنفيذية', value: '18 / 2026' },
        { label: 'رقم الإشارة', value: 'هـ/رق/512' },
        { label: 'المهلة الزمنية للتطبيق', value: '30 يوماً' },
      ],
      followUpAssignees: [
        {
          entityName: 'مسؤول الأمن السيبراني وضابط الامتثال',
          assignedAction: 'لتطبيق السياسات وإجراء الفحص الأمني للأرشيف',
          deadline: '2026/06/15',
          status: 'قيد المتابعة',
        },
        {
          entityName: 'مدراء الفروع والمحافظات',
          assignedAction: 'للاطلاع والالتزام والتعميم على الأقسام',
          status: 'قيد المتابعة',
        },
      ],
      attachments: ['الدليل الإجرائي الموحد لأمن الوثائق الإلكترونية (نسخة معتمدة)'],
      blueStamp: {
        detected: true,
        handwrittenIncomingNumber: '2089/و',
        handwrittenReceiptDate: '2026/05/15',
        stampPrintedText: 'شعبة الوارد السري والبريد المباشر',
        confidence: 95,
        notes: 'الختم الأزرق موجود ومكتوب بداخله رقم الوارد 2089/و بتاريخ 15 مايو 2026.',
        boundingBox: {
          topPercent: 12.8,
          leftPercent: 7.5,
          widthPercent: 27,
          heightPercent: 10.5,
        },
      },
      pageImages: [sampleCanvas2],
      pdfFileName: 'دليل_أمن_الوثائق_السيبراني_2089.pdf',
      pdfFileSize: 512000,
      createdAt: '2026-05-15T11:00:00.000Z',
      updatedAt: '2026-05-15T11:00:00.000Z',
    },
  ];
}
